# Generated by Django 3.2.5 on 2021-07-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiop_api', '0002_auto_20210716_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectexample',
            name='theme',
            field=models.CharField(choices=[('AG', 'Agua'), ('EN', 'Energia'), ('MO', 'Mobilidade'), ('AM', 'Ambiente'), ('RE', 'Reciclagem')], max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Reporter',
        ),
    ]
