# Generated by Django 3.2.5 on 2021-07-16 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wikiop_api', '0003_auto_20210716_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimarySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecondarySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('PrimarySection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikiop_api.primarysection')),
            ],
        ),
    ]
