# Generated by Django 3.2.5 on 2021-07-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiop_api', '0004_primarysection_secondarysection'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True)),
                ('Description', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='primarysection',
            name='Description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='primarysection',
            name='Name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
