# Generated by Django 3.2.5 on 2021-07-16 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wikiop_api', '0005_auto_20210716_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAndAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=200)),
                ('answerText', models.TextField(max_length=200)),
                ('fixedSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikiop_api.fixedsection')),
                ('primarySection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikiop_api.primarysection')),
                ('secondarySection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikiop_api.secondarysection')),
            ],
        ),
    ]
