# Generated by Django 3.2.5 on 2021-07-18 16:24

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('wikiop_api', '0006_questionandanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixedsection',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='fixedsection',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='primarysection',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='primarysection',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='questionandanswer',
            old_name='fixedSection',
            new_name='fixed_section',
        ),
        migrations.RenameField(
            model_name='questionandanswer',
            old_name='primarySection',
            new_name='primary_section',
        ),
        migrations.RenameField(
            model_name='secondarysection',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='secondarysection',
            old_name='PrimarySection',
            new_name='primary_section',
        ),
        migrations.RemoveField(
            model_name='questionandanswer',
            name='secondarySection',
        ),
        migrations.AddField(
            model_name='questionandanswer',
            name='secondary_section',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='primary_section', chained_model_field='primary_section', default=1, on_delete=django.db.models.deletion.CASCADE, to='wikiop_api.secondarysection'),
            preserve_default=False,
        ),
    ]
