# Generated by Django 3.2.5 on 2021-07-18 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wikiop_api', '0007_auto_20210718_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionandanswer',
            old_name='answerText',
            new_name='answer_text',
        ),
        migrations.AlterField(
            model_name='questionandanswer',
            name='fixed_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wikiop_api.fixedsection'),
        ),
        migrations.AlterField(
            model_name='questionandanswer',
            name='primary_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wikiop_api.primarysection'),
        ),
        migrations.AlterField(
            model_name='secondarysection',
            name='primary_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wikiop_api.primarysection'),
        ),
    ]
