# Generated by Django 3.2.5 on 2021-07-21 09:07

from django.db import migrations, models
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiop_api', '0010_alter_secondarysection_primary_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionandanswer',
            name='answer_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='questionandanswer',
            name='answer_text_rendered',
            field=markdownfield.models.RenderedMarkdownField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionandanswer',
            name='warning_text',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='questionandanswer',
            name='answer_text',
            field=markdownfield.models.MarkdownField(rendered_field='answer_text_rendered'),
        ),
    ]
