# Generated by Django 3.2.5 on 2021-07-22 09:48

from django.db import migrations, models
import django.db.models.deletion
import markdownfield.models
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('wikiop_api', '0011_auto_20210721_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionandanswer',
            name='other_sources',
            field=markdownfield.models.MarkdownField(default='', help_text='other sources about the current theme', rendered_field='other_sources_rendered'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionandanswer',
            name='other_sources_rendered',
            field=markdownfield.models.RenderedMarkdownField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionandanswer',
            name='relevant_documents',
            field=markdownfield.models.MarkdownField(default='', help_text='relevant documents with important information to answer this question', rendered_field='relevant_documents_rendered'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionandanswer',
            name='relevant_documents_rendered',
            field=markdownfield.models.RenderedMarkdownField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionandanswer',
            name='answer_file',
            field=models.FileField(blank=True, help_text='image or video to answer the question (optional)', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='questionandanswer',
            name='answer_text',
            field=markdownfield.models.MarkdownField(help_text='the full answer to the question asked, possible to add links', rendered_field='answer_text_rendered'),
        ),
        migrations.AlterField(
            model_name='questionandanswer',
            name='primary_section',
            field=models.ForeignKey(help_text='main sections/themes of the website (AGUA, AMBIENTE ...)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question', to='wikiop_api.primarysection'),
        ),
        migrations.AlterField(
            model_name='questionandanswer',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionandanswer',
            name='secondary_section',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='primary_section', chained_model_field='primary_section', help_text='secondary sections/themes for each primary section', on_delete=django.db.models.deletion.CASCADE, related_name='question', to='wikiop_api.secondarysection'),
        ),
        migrations.AlterField(
            model_name='questionandanswer',
            name='warning_text',
            field=models.TextField(blank=True, help_text='the text shown in red at the end of the answer section (optional)', max_length=2000),
        ),
    ]
