# Generated by Django 3.2.5 on 2021-07-22 14:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiop_api', '0012_auto_20210722_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='projectexample',
            old_name='text',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='projectexample',
            name='name',
        ),
        migrations.AddField(
            model_name='projectexample',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=40000, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectexample',
            name='link',
            field=models.URLField(default='https://www.google.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectexample',
            name='year',
            field=models.IntegerField(default=2021, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectexample',
            name='theme',
            field=models.ForeignKey(help_text='main sections/primarysections of the website (AGUA, AMBIENTE ...)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_example', to='wikiop_api.primarysection'),
        ),
        migrations.AlterField(
            model_name='questionandanswer',
            name='answer_text',
            field=markdownfield.models.MarkdownField(blank=True, help_text='the full answer to the question asked, possible to add links', null=True, rendered_field='answer_text_rendered'),
        ),
        migrations.AlterField(
            model_name='questionandanswer',
            name='other_sources',
            field=markdownfield.models.MarkdownField(blank=True, help_text='other sources about the current theme', null=True, rendered_field='other_sources_rendered'),
        ),
        migrations.AlterField(
            model_name='questionandanswer',
            name='relevant_documents',
            field=markdownfield.models.MarkdownField(blank=True, help_text='relevant documents with important information to answer this question', null=True, rendered_field='relevant_documents_rendered'),
        ),
        migrations.AddField(
            model_name='projectexample',
            name='identification',
            field=models.ForeignKey(help_text='main sections/primarysections of the website (AGUA, AMBIENTE ...)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question', to='wikiop_api.projectidentification'),
        ),
    ]
