# Generated by Django 3.2.5 on 2021-07-26 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiop_api', '0013_auto_20210722_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectexample',
            name='identification',
        ),
        migrations.AddField(
            model_name='projectexample',
            name='intention',
            field=models.CharField(default='nothin', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectexample',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1800)]),
        ),
        migrations.DeleteModel(
            name='ProjectIdentification',
        ),
    ]
