# Generated by Django 3.2.5 on 2021-07-26 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_auto_20210726_0932'),
        ('wikiop_api', '0014_auto_20210726_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectexample',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_example', to='cities_light.city'),
        ),
    ]
